baseURL = "https://stevehora.netlify.com"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
disableLanguages = ["Fr"]
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "Vedic"
title = "Vedic Astrology Advice"
[Languages.en]
contentDir = "content/english"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[menu.main]]
URL = "about"
name = "About Us"
weight = 1
[[menu.main]]
URL = "services"
name = "Solutions"
weight = 2
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3
[[menu.main]]
URL = "team"
name = "Team"
weight = 4
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 6
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 7
[params]
author = "Steve Hora"
description = "Vedic Astrology Advice"
googleAnalitycsID = "UA-87949467-1"
logo = "images/shrichakra.png"
postShare = true
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/animate-css/animate.css"
[[params.plugins.css]]
URL = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.js]]
URL = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
URL = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
URL = "plugins/wow/wow.min.js"
[params.preloader]
enable = true
preloader = "images/shrichakra.png"
[[params.social_Icon]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/SteveHoraAstrologer/"
[[params.social_Icon]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/AstrologyOrbit"
[[params.social_Icon]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "https://www.youtube.com/channel/UCakwfKTqhG9rjpmvQLAsYxA"
[[params.social_Icon]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/steve-hora-astrologer-horoscope-prediction-expert-2880a3101/"
